title: img.crypt
description: "A set of basic image encryption tools and obfuscators, made just for fun."
owner_name: Ian W.
github_username: iwu78
github_username2: monke7760
github_username3: RyanZLiu
github_username4: SrijDude3416
github_repo: "Nighthawk-Pages"
baseurl: "/binary"
author-image: assets/images/gif.gif
# remote_theme: jekyll/minima 
remote_theme: thedevslot/WhatATheme
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
